SHOPHERE/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('Accounts/',include('Accounts.urls')),
    path('product/',include('product.urls')),
    path('contact/',include('contact.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('about/',views.about,name='about')
]

product/models.py
from email.headerregistry import Group

from django.db import models
from datetime import datetime
from Accounts.models import User
from .choices import CATEGORY_CHOICE,PRODUCT_COLOR,AVAILABILITY_CHOICE,RETURN_POLICY,COMPANY_NAME
# Create your models here.

class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    mobile_number = models.CharField(max_length=10, default=None)
    address = models.TextField(max_length=300, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, default='Noida', null=True)
    state = models.CharField(max_length=100, blank=True, default=None, null=True)
    postal_code = models.IntegerField(blank=True, default=None, null=True)
    age = models.IntegerField(default=20, null=True)
    gender = models.CharField(max_length=10, default='Male', null=True)
    country = models.CharField(max_length=50, blank=True, default=None, null=True)
    additional_information = models.TextField(max_length=100000, null=True, blank=True)
    image = models.ImageField(upload_to='Accounts', default=None, blank=True)
    shop_name=models.CharField(max_length=100,default=None,blank=True,null=True)
    shop_GST_no=models.CharField(max_length=100,default=None,blank=True,null=True)
    aadhar_card_no=models.CharField(max_length=100,default=None,blank=True,null=True)
    aadhar_pic=models.ImageField(upload_to='Accounts',default=None,blank=True,null=True)

    def __str__(self):
        return self.user.username
class Product(models.Model):
    seller=models.ForeignKey(Seller,on_delete=models.CASCADE)
    ProductName=models.CharField(max_length=100,default=None)
    description = models.TextField(max_length=300000, default=None)
    category = models.CharField(max_length=100,default=None)
    brand=models.CharField(max_length=100,default=None)
    price=models.IntegerField(default=None,blank=True,null=True)
    quantity = models.IntegerField(default=None)
    stock=models.CharField(max_length=100,default=None,blank=True,null=True)
    color=models.CharField(max_length=100,default=None,blank=True)
    return_policy=models.CharField(max_length=100,default=None,blank=True)
    delivery_charge=models.IntegerField(default=0,blank=True,null=True)
    main_photo=models.ImageField(upload_to='products',blank=True)
    optional_photo1=models.ImageField(upload_to='products',blank=True)
    optional_photo2=models.ImageField(upload_to='products',blank=True)
    optional_photo3=models.ImageField(upload_to='products',blank=True)
    publish_date=models.DateTimeField(auto_now_add=False,auto_now=True)
    Discount_percent = models.IntegerField(default=0,blank=True,null=True)
    sale_price = models.IntegerField(default=0, blank=True, null=True)
    Terms_conditions = models.CharField(max_length=100000, default=None, blank=True,null=True)
    offer_description = models.TextField(max_length=100000, default=None,blank=True,null=True)

    class Meta:
        permissions=('edit_product','Can add product'),

    def __str__(self):
        return '{} by {}'.format(self.ProductName.upper(),self.seller.user.username.upper())

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=0)
    status=models.BooleanField(default=False)

    def __str__(self):
        return '{} by {}'.format(self.product.ProductName,self.user.username)
class Order(models.Model):
    cust_id=models.ForeignKey(User,on_delete=models.CASCADE)
    prd_id=models.CharField(max_length=100)
    cart_id=models.CharField(max_length=100)
    inv_id=models.CharField(max_length=100)
    status=models.BooleanField(default=False)
    order_date=models.DateTimeField(auto_now_add=False,auto_now=True)

    def __str__(self):
        return self.cust_id.username

templates/partials/alerts.html
{% if messages %}
{% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissable text-center" role="alert">
    <button type="button"class="close" data-dismiss='alert'><span aria-hidden="true">&times;</span></button>
    <strong>
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      Error:
      {% else %}
      {{ title }}
      {% endif %}
    </strong>
    {{ message }}
  </div>
{% endfor %}
{% endif %}

templates/partials/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
      {% load static %}
    <meta charset="utf-8">
    <title> Bootshop online Shopping cart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
<!--Less styles -->
   <!-- Other Less css file //different less files has different color scheam
	<link rel="stylesheet/less" type="text/css" href="themes/less/simplex.less">
	<link rel="stylesheet/less" type="text/css" href="themes/less/classified.less">
	<link rel="stylesheet/less" type="text/css" href="themes/less/amelia.less">  MOVE DOWN TO activate
	-->
	<!--<link rel="stylesheet/less" type="text/css" href="themes/less/bootshop.less">
	<script src="themes/js/less.js" type="text/javascript"></script> -->

<!-- Bootstrap style -->
    <link id="callCss" rel="stylesheet" href="{% static 'themes/bootshop/bootstrap.min.css'%}" media="screen"/>
    <link href="{% static 'themes/css/base.css' %}" rel="stylesheet" media="screen"/>
<!-- Bootstrap style responsive -->
	<link href="{% static 'themes/css/bootstrap-responsive.min.css'%}" rel="stylesheet"/>
	<link href="{% static 'themes/css/font-awesome.css'%}" rel="stylesheet" type="text/css">
<!-- Google-code-prettify -->
	<link href="{% static 'themes/js/google-code-prettify/prettify.css'%}" rel="stylesheet"/>
      <!-- style sheet for manual editing -->
      <link href="{% static 'themes/css/style.css'%}" rel="stylesheet"/>
<!-- fav and touch icons -->
    <link rel="shortcut icon" href="{% static 'themes/images/ico/favicon.ico'%}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'themes/images/ico/apple-touch-icon-144-precomposed.png'%}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'themes/images/ico/apple-touch-icon-114-precomposed.png'%}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'themes/images/ico/apple-touch-icon-72-precomposed.png'%}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'themes/images/ico/apple-touch-icon-57-precomposed.png'%}">
	<style type="text/css" id="enject"></style>
      <!--about page of other template-->
      <!-- Custom-Files -->
	<link href="{% static 'about/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- Bootstrap css -->
	<link href="{% static 'css/style1.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- Main css -->
	<link rel="stylesheet" href="{% static 'css/fontawesome-all.css' %}">
	<!-- Font-Awesome-Icons-CSS -->
	<link href="{% static 'css/popuo-box.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- pop-up-box -->
	<link href="{% static 'css/menu.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- menu style -->
	<!-- //Custom-Files -->
      <!--style1.css-->
      <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />

	<!-- web fonts -->
	<link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&amp;subset=latin-ext" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese"
	    rel="stylesheet">
	<!-- //web fonts -->
       <!-- Date Time Picker CSS -->
  <link rel="stylesheet" href="{% static 'date-time-phone/jquery-ui.css' %}">
  <link rel='stylesheet' href="{% static 'date-time-phone/jquery-ui-timepicker-addon.css' %}">
  <!-- Date Time Picker CSS -->

  </head>
 <body>
 {% include 'partials/header.html' %}
 {% include 'partials/navbar.html' %}
 {% block content %} {% endblock %}
 {% include 'partials/footer.html' %}
 <!-- jQuery Plugins -->
	<script src="{% static 'themes/js/jquery.js'%}" type="text/javascript"></script>
	<script src="{% static 'themes/js/bootstrap.min.js'%}" type="text/javascript"></script>
	<script src="{% static 'themes/js/google-code-prettify/prettify.js'%}"></script>
 	<script src="{% static 'themes/js/bootshop.js'%}"></script>
 	<script src="{% static 'themes/js/jquery.lightbox-0.5.js'%}"></script>
 <!--js files of about page-->
 	<!-- //smooth-scrolling-of-move-up -->

	<!-- for bootstrap working -->
	<script src="{% static 'about/js/bootstrap.js' %}"></script>
	<!-- //for bootstrap working -->
	<!-- //js-files -->
 <!-- Date time picker-->
 <script src="{% static 'date-time-phone/jquery-ui.js' %}" ></script>
 <script src="{% static 'date-time-phone/jquery-ui-timepicker-addon.js' %}"></script>
 <script>
    $( function() {
        // $( "#id_publish_date" ).datetimepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
        // $( "#id_publish_date" ).timepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
        $( "#id_publish_date" ).datepicker({ dateFormat: 'yy-mm-dd' }).attr("autocomplete", "off") ;
    });
  </script>
<!-- jquery <
    <script src="{% static 'jquery.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js1' %}"></script>

    jquery-->




</body>
</html>

templates/partials/common item.html
{% load static %}
<div id="sidebar" class="span3">
		<div class="well well-small"><a id="myCart" href="{% url 'cart_data' %}"><img src="{% static 'themes/images/ico-cart.png' %}" alt="cart">{{items}} Items in your cart  <span class="badge badge-warning pull-right">Rs{{sale_price}}</span></a></div>
		<ul id="sideManu" class="nav nav-tabs nav-stacked">
			{% for keys,values in product_by_name.items %}
				{% for key,val in values.items %}
			<li class="subMenu open"><a>{{keys}}<i class="icon-chevron-right"></i>[{{key}}]</a>
				<ul style="display:none">
					{% for keyss,vals in val.items %}
						<li><a class="active"  href="{% url 'product_by_category' %}"><i class="icon-chevron-right"></i>{{keyss}} [{{vals}}] </a></li>
						{% endfor %}

				</ul>
			</li>
			{% endfor %}
			{% endfor %}
		</ul>
	<br/>
	<center>
		<p style="font-size:18px;">
			<bold>Latest Products</bold>
		</p>
		</center>
		  <div class="thumbnail">
			  {% if latest_product %}
			  	{% for product in latest_product|slice:":3" %}
			  		{% if product.main_photo %}
						<img src="{{product.main_photo.url}}" alt=""/>
			  		{% else %}
			  			<img src="{% static 'images/profile pic1.jpg' %}"
			  		{% endif %}
			  		<div class="caption">
					  	<h5>{{ product.ProductName.upper }}</h5>
						<h4 style="text-align:center"><a class="btn" href="{% url 'product_detail' product.id %}"> <i class="icon-zoom-in"></i></a> <a class="btn" href="{% url 'add_to_cart' product.id %}">Add to <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">RS {{ product.price }}</a></h4>
						 <p>
							 {{ product.description|slice:":50" }}
						 </p>
					</div>
			  	{% endfor %}
			  {% endif %}
		  </div><br/>
	</div>




























<!-- Sidebar ================================================== -->
	<!--<div id="sidebar" class="span3">
		<div class="well well-small"><a id="myCart" href="product_summary.html"><img src="themes/images/ico-cart.png" alt="cart">3 Items in your cart  <span class="badge badge-warning pull-right">$155.00</span></a></div>
		<ul id="sideManu" class="nav nav-tabs nav-stacked">
			{% for item in category %}
			<li class="subMenu open">
				<li><a href="products.html" {{ item | first }}><i class="icon-chevron-right"></i></a></li>
					<ul>
						<li><a class="active" href="products.html"><i class="icon-chevron-right"></i>Cameras (100) </a></li>
					</ul>
			</li>
			<li class="subMenu open">
				<a>{{item|slice:"1:"}}<i class="icon-chevron-right"></i></a>
				<ul style="display:none">
				<li><a href="products.html"><i class="icon-chevron-right"></i>Women's Clothing</a></li>
				</ul>
			</li>
			{% endfor %}
		</ul>
		<br/>
		  <div class="thumbnail">
			<img src="themes/images/products/panasonic.jpg" alt="Bootshop panasonoc New camera"/>
			<div class="caption">
			  <h5>Panasonic</h5>
				<h4 style="text-align:center"><a class="btn" href="product_details.html"> <i class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">$222.00</a></h4>
			</div>
		  </div><br/>
			<div class="thumbnail">
				<img src="themes/images/products/kindle.png" title="Bootshop New Kindel" alt="Bootshop Kindel">
				<div class="caption">
				  <h5>Kindle</h5>
				    <h4 style="text-align:center"><a class="btn" href="product_details.html"> <i class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">$222.00</a></h4>
				</div>
			  </div><br/>
	</div>-->

templates/partials/dashboard_base.html
{% extends 'partials/main_base4_dashboard.html'%}
{% load static %}
{% block content %}
 {% if user.is_superuser %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 mt-4">
                <div class="jumbotron">
                    <h1>Sorry Mr./Miss {{user.username}} You are not allowed Here</h1>
                </div>
            </div>
        </div>
    </div>
{% else %}
<div class="container-fluid">
    <div class="row">
        <!-- left side menu -->
        <!-- right side menu -->
        <div class="col-md-10">
            {% block dashboard %}

            {% endblock %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/partials/footer.html
<!-- FOOTER -->
{% load static %}
	<div  id="footerSection">
	<div class="container">
		<div class="row">
			<div class="span3">
				<h5>ACCOUNT</h5>
				{% if request.user.is_authenticated %}
					<a href="{% url 'logout' %}">LOGOUT</a>
				{% else %}
					<a href="{% url 'login' %}">LOGIN</a>
				{% endif %}
				{% if request.user.is_staff %}
	 		<li class=""><a href="{% url 'sellerdashboard' %}">My Profile</a></li>
		  {% else %}
		  	<li class=""><a href="{% url 'custdashboard' %}">My Profile</a></li>
		  {% endif %}
			 </div>
			<div class="span3">
				<h5>INFORMATION</h5>
				<a href="{% url 'about' %}">ABOUT</a>
				<a href="{% url 'contact' %}">CONTACT</a>
				<a href="{% url 'legal_notice' %}">LEGAL NOTICE</a>
				<a href="{% url 'tac'%}">TERMS AND CONDITIONS</a>
				<a href="{% url 'faq'%}">FAQ</a>
			 </div>
			<div class="span3">
				<h5>OUR OFFERS</h5>
				<a href="{% url 'index' %}">NEW PRODUCTS</a>
				<a href="{% url 'sellers' %}">TOP SELLERS</a>
				<a href="{% url 'special_offers' %}">SPECIAL OFFERS</a>
			 </div>
			<div id="socialMedia" class="span3 pull-right">
				<h5>SOCIAL MEDIA </h5>
				<a href="#"><img width="60" height="60" src="{% static 'themes/images/facebook.png'%}" title="facebook" alt="facebook"/></a>
				<a href="#"><img width="60" height="60" src="{% static 'themes/images/twitter.png'%}" title="twitter" alt="twitter"/></a>
				<a href="#"><img width="60" height="60" src="{% static 'themes/images/youtube.png'%}" title="youtube" alt="youtube"/></a>
			 </div>
		 </div>
		<p class="pull-right">&copy; Bootshop</p>
	</div><!-- Container End -->
	</div>

templates/partials/header.html
{% load static %}
	<div id="header">
<div class="container">
<div id="welcomeLine" class="row">
	<div class="span6">Welcome!<strong>{{ user.username}}</strong></div>
	</div>
</div>
	</div>

templates/partials/main_base4_dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
      {% load static %}
    <meta charset="utf-8">
      <!-- Bootstrap style -->
    <link id="callCss" rel="stylesheet" href="{% static 'themes/bootshop/bootstrap.min.css'%}" media="screen"/>
    <link href="{% static 'themes/css/base.css'%}" rel="stylesheet" media="screen"/>
<!-- Bootstrap style responsive -->
	<link href="{% static 'themes/css/bootstrap-responsive.min.css'%}" rel="stylesheet"/>
	<link href="{% static 'themes/css/font-awesome.css'%}" rel="stylesheet" type="text/css">
<!-- Google-code-prettify -->
	<link href="{% static 'themes/js/google-code-prettify/prettify.css'%}" rel="stylesheet"/>
      <!-- style sheet for manual editing -->
      <link href="{% static 'themes/css/style.css'%}" rel="stylesheet"/>
<!-- fav and touch icons -->
    <link rel="shortcut icon" href="{% static 'themes/images/ico/favicon.ico'%}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'themes/images/ico/apple-touch-icon-144-precomposed.png'%}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'themes/images/ico/apple-touch-icon-114-precomposed.png'%}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'themes/images/ico/apple-touch-icon-72-precomposed.png'%}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'themes/images/ico/apple-touch-icon-57-precomposed.png'%}">
	<style type="text/css" id="enject"></style>
      <!--about page of other template-->
      <!-- Custom-Files -->
	<link href="{% static 'about/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- Bootstrap css -->
	<link href="{% static 'css/style1.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- Main css -->
	<link rel="stylesheet" href="{% static 'css/fontawesome-all.css' %}">
	<!-- Font-Awesome-Icons-CSS -->
	<link href="{% static 'css/popuo-box.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- pop-up-box -->
	<link href="{% static 'css/menu.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- menu style -->
	<!-- //Custom-Files -->
      <!--style1.css-->
      <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />

	<!-- web fonts -->
	<link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&amp;subset=latin-ext" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese"
	    rel="stylesheet">
	<!-- //web fonts -->

    <title>Bootshop online Shopping cart</title>
      {% include 'partials/header.html' %}
      {% include 'partials/navbar.html' %}
          {% block content %}
            {% endblock %}
{% include 'partials/footer.html' %}
      <script src="{% static 'themes/js/jquery.js'%}" type="text/javascript"></script>
	<script src="{% static 'themes/js/bootstrap.min.js'%}" type="text/javascript"></script>
	<script src="{% static 'themes/js/google-code-prettify/prettify.js'%}"></script>
 	<script src="{% static 'themes/js/bootshop.js'%}"></script>
 	<script src="{% static 'themes/js/jquery.lightbox-0.5.js'%}"></script>
 <!--js files of about page-->
 	<!-- //smooth-scrolling-of-move-up -->

	<!-- for bootstrap working -->
	<script src="{% static 'about/js/bootstrap.js' %}"></script>
	<!-- //for bootstrap working -->
	<!-- //js-files -->

templates/partials/navbar.html
{% load static%}
<div id="logoArea" class="navbar">
<a id="smallScreen" data-target="#topMenu" data-toggle="collapse" class="btn btn-navbar">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
</a>
  <div class="navbar-inner">
    <a class="brand" href="{% url 'index' %}"><img src="{% static 'themes/images/logo.png'%}" alt="Bootsshop"/></a>

		<form class="form-inline navbar-search" action="{% url 'products' %}">
			<select class="srchTxt" type="text" id="category" name="category">
			<label for="category">category</label>
				<option selected="true" disabled="disabled">CATEGORY</option>
				<option>CLOTHING </option>
				<option>FOOD</option>
				<option>ELECTRONICS </option>
				<option>SPORTS</option>
				<option>BOOKS</option>
				<option>COSMETICS</option>
				<option>FOOTWEAR</option>
		</select>
		  <button type="submit" id="submitButton" class="btn btn-primary">Go</button>
        </form>
	  <ul id="topMenu" class="nav pull-right">
		  {% if user.is_authenticated %}
			  {% if user.is_staff and user.is_superuser %}
				<li class=""><a href="{% url 'adminprofile' %}">View Profile</a></li>
			  {% elif user.is_staff %}
				<li class=""><a href="{% url 'sellerdashboard' %}">View Profile</a></li>
		      {% else %}
		  		<li class=""><a href="{% url 'custdashboard' %}">View Profile</a></li>

			  {% endif %}
		  {% endif %}
		  {% if user.is_staff %}
	 		<li class=""><a href="{% url 'seller_edit_profile' %}">Edit Profile</a></li>
		  {% else %}
		  <li class=""><a href="{% url 'customer_edit_profile' %}">Edit Profile</a></li>
		  {% endif %}
	  <li class=""><a href="{% url 'changepass' %}">Change Password</a></li>
	<li class=""><a href="{% url 'products' %}"> View Products</a></li>
		  {% if user.is_staff and not user.is_superuser %}
		  <li class=""><a href="{% url 'my_products' %}"> My Registered Products</a></li>
		  <li class=""><a href="{% url 'add_products' %}">Add Products</a></li>
		  {% endif %}

	 <li class=""><a href="{% url 'order_history' %}">My Orders</a></li>
		  <li class=""><a href="{% url 'cart_data' %}">My Cart</a></li>
		  <!--<li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">My profile<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
			  </ul>
            </li>-->

		{% if request.user.is_authenticated %}
	 <a href="{% url 'logout' %}" role="button" data-toggle="modal" style="padding-right:0"><span class="btn btn-large btn-success">Logout</span></a>
	<div id="logout" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="logout" aria-hidden="false" ></div>
	</li>
		{% else %}
	 <a href="{% url 'login' %}" role="button" data-toggle="modal" style="padding-right:0"><span class="btn btn-large btn-success">Login</span></a>
	<div id="login" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="login" aria-hidden="false" ></div>
	</li>

	  <a href="{% url 'signup' %}" role="button" data-toggle="modal" style="padding-right:0"><span class="btn btn-large btn-success">Signup</span></a>
	<div id="signup" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="logout" aria-hidden="false" ></div>
	</li>

		{% endif %}
    </ul>
  </div>
</div>
</div>
</div>
<!-- Header End====================================================================== -->

templates/partials/offer_slide.html
{% load static %}
<div id="carouselBlk">
	<div id="myCarousel" class="carousel slide">
		<div class="carousel-inner">
		  <div class="item active">
		  <div class="container">
			<a href="{% url 'special_offers' %}"><img style="width:100%" src="{% static 'themes/images/carousel/1.png' %}" alt="special offers"/></a>
			<div class="carousel-caption">
				  <h4>Second Thumbnail label</h4>
				  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
				</div>
		  </div>
		  </div>
		  <div class="item">
		  <div class="container">
			<a href="{% url 'special_offers' %}"><img style="width:100%" src="{% static 'themes/images/carousel/2.png' %}" alt=""/></a>
				<div class="carousel-caption">
				  <h4>Second Thumbnail label</h4>
				  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
				</div>
		  </div>
		  </div>
		<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
	  </div>
</div>